name: Export Secret
run-name: Export Secret | env ${{ github.event.inputs.env }}

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        default: "dev"
        options:
          - dev
          - sit

jobs:
  export-secret:
    name: Export secret ${{ github.event.inputs.env }} environment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout pipelines
        uses: actions/checkout@v4

      - name: List working directory
        run: ls -l

      - name: Echo secret
        run: |
          echo "$SECRETS_CONTEXT" >> secret_${{ github.event.inputs.env }}.json
          echo "$VARIABLE" >> var_${{ github.event.inputs.env }}.json
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          VARIABLE: ${{ toJson(vars)}}

      - uses: actions/upload-artifact@v4
        with:
          name: export-secret-variables-${{ github.event.repository.name }}-${{ github.event.inputs.env }}
          path: |
            secret_${{ github.event.inputs.env }}.json
            var_${{ github.event.inputs.env }}.json
